#####################################################
#WhosOnline!#########################################
#####################################################

Menu:
  Title: "&8&lPlayers Online&r"
  Forward:
     Material: ARROW
     Name: "&f&lNext Page"
  Previous:
     Material: ARROW
     Name: "&f&lPrevious Page"